services:
  app:
    image: ozzzernova/ping_pong:0.0.1
    build: .
    ports:
      - "5000:5000"
    environment:
      POSTGRES_DB: ping_pong_db
      POSTGRES_USER: ozzzernova
      POSTGRES_PASSWORD: megagigapassword
      POSTGRES_HOST: db
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ping_pong_db
      POSTGRES_USER: ozzzernova
      POSTGRES_PASSWORD: megagigapassword
      
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

