services:
  host_1:
    build: ./hosts
    tty: true
    networks:
      - internal-net

  host_2:
    build: ./hosts
    tty: true
    networks:
      - internal-net

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ping_pong_db
      POSTGRES_USER: ozzzernova
      POSTGRES_PASSWORD: megagigapassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal-net
  
  jenkins:
    build: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ./jenkins_data:/var/jenkins_home
      - ./ansible:/ansible
    networks:
      - internal-net

  sonarqube:
    image: sonarqube
    depends_on:
      - sonar_db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar_db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - ./sonarqube/sonarqube_data:/opt/sonarqube/data
      - ./sonarqube/sonarqube_extensions:/opt/sonarqube/extensions
      - ./sonarqube/sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
    networks:
      - internal-net

  sonar_db:
    image: postgres
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    networks:
      - internal-net
    

networks:
  internal-net:
    driver: bridge

volumes:
  postgres_data:

